### ISSUE TITLE
Same old baffling analysis problem

### ISSUE THREAD

**Issue by janedupuy** [marvinmarnold/stingraymappingproject.org#10]
Becky: "For descriptive purposes it sounds like you’ll have timely and precise data.  It strikes me that in order to really understand the causes (and potential consequences) of Stingray use, you will have to more carefully articulate how and what other data you’ll collect.  I suspect that the impact of your research would be significantly strengthened with more attention to selectivity in who downloads the app (and who doesn’t) and how that might vary in relation to socio-demographic characteristics and geography.  I’m also concerned that no evidence of a Stingray surveillance is a pretty muddled signal."

**Comment by marvinmarnold** [comment]
I don't think you meant to close this did you?

**Comment by marvinmarnold** [comment]
Oh maybe you did mean to
