### ISSUE TITLE
Get Involved Page

### ISSUE THREAD

**Issue by janedupuy** [marvinmarnold/stingraymappingproject.org#12]
What if this read instead:

We’ve created a modified version of an Android app to notify you when your device is likely connected to a Stingray and to plot those threats onto the map on this site. We won't collect any information that would identify you or your phone, only a Stingray threat level, time stamp, and GPS coordinates. This data will help us understand patterns of Stingray use, including which neighborhoods and political events are targeted.

**Comment by marvinmarnold** [comment]
If you make edits, can you keep the embedded HTML so that I can always just copy and paste, tx.

We’ve created a modified version of an <a href="https://github.com/SecUpwN/Android-IMSI-Catcher-Detector">existing Android app</a> to notify you when your device is likely connected to a Stingray and to plot those threats onto the map on this site. We won't collect any information that would identify you or your phone, only a Stingray threat level, time stamp, and GPS coordinates. This data will help us understand patterns of Stingray use, including which neighborhoods and political events are targeted.

**Comment by marvinmarnold** [comment]
Rather, keep the links in tact.

**Comment by janedupuy** [comment]
Yep

**Comment by janedupuy** [comment]
Oh, you just added that, got it. In theYes, I'll leave it alone!

**Comment by marvinmarnold** [comment]
Oh I meant, moving forward copying from this Issue. This really isn't the best way to handle it but it should do for now.

Here is some content I'm going to add below:

This project runs on three different open source projects. If you can code, please fork the project and send us some pull requests.

**Comment by janedupuy** [comment]
Sounds great! In the spirit of our little codependent relationship, heads
up that I'm heading to a meeting and then gone for the night :) Great
hanging out today

**Comment by marvinmarnold** [comment]
Download the App
We’ve created a modified version of an <a href="https://github.com/SecUpwN/Android-IMSI-Catcher-Detector">existing Android app</a> to notify you when your device is likely connected to a Stingray and to plot those threats onto the map on this site. We won't collect any information that would identify you or your phone, only a Stingray threat level, time stamp, and GPS coordinates. This data will help us understand patterns of Stingray use, including which neighborhoods and political events are targeted.

Contribute to Development
This project runs on three different open source projects. If you can code, please fork the project and send us some pull requests.

App
- Built with Android
- Forked from an <a href="https://github.com/SecUpwN/Android-IMSI-Catcher-Detector">existing Android app</a>
- Get the source <a href="https://github.com/marvinmarnold/Android-IMSI-Catcher-Detector">here</a>

Website
- Built with Meteor
- Get the source <a href="https://github.com/marvinmarnold/stingraymappingproject.org">here</a>

Database Server
- Built with Ruby on Rails
- Get the source <a href="https://github.com/marvinmarnold/imsi-mapper">here</a>

**Comment by marvinmarnold** [comment]
Download the App
We’ve created a modified version of an existing Android app to notify you when your device is likely connected to a Stingray and to plot those threats onto the map on this site. We won't collect any information that would identify you or your phone, only a Stingray threat level, time stamp, and GPS coordinates. This data will help us understand patterns of Stingray use, including which neighborhoods and political events are targeted.

Contribute to Development
This project runs on three different open source projects. If you can code, please fork the project and send us some pull requests.

App
- Built with Android
- Forked from an <a href="https://github.com/SecUpwN/Android-IMSI-Catcher-Detector">existing Android app</a>
- Get the source <a href="https://github.com/marvinmarnold/Android-IMSI-Catcher-Detector">here</a>

Website
- Built with Meteor
- Get the source <a href="https://github.com/marvinmarnold/stingraymappingproject.org">here</a>

Database Server
- Built with Ruby on Rails
- Get the source <a href="https://github.com/marvinmarnold/imsi-mapper">here</a>

Contact the Team
Feel free to contact <a href="mailto:mary.ellen.stitt@gmail.com">Mary Ellen Stitt</a> or <a href="mailto:marvin@unplugged.im">Marvin Arnold</a> about this site. Mary Ellen is a student, Marvin is a programmer, and we both live in New Orleans. We want to make this site as useful as possible, so we welcome all questions and feedback!

**Comment by marvinmarnold** [comment]
We should do a better job of giving credit to the core AIMSICD detection project. Can you take a stab at adding a sentence somewhere that more expressly thanks them?

**Comment by janedupuy** [comment]
How about right after the first paragraph about "download the app," something like

This project owes its existence to the incredible work of the AIMSICD detection project [link], which created and continues to refine the Stingray detection technology on which the app relies.

**Comment by janedupuy** [comment]
Also could you have "contribute to development" be a link that takes people to the three sections right below that? or put "more information here" and have that link to it? I don't want non-tech people to try to get confused by all that stuff.

Re: our bio, I could have sworn I'd put your name first. Let's switch that.

**Comment by marvinmarnold** [comment]
What if I move contact the team above contribute to development? I'm OK obscuring the tech stuff a little but I don't want to make it a second class citizen. 

you will always be first in my book.

**Comment by janedupuy** [comment]
Okay to put the tech stuff at the bottom. Let's just make sure we indent those three headings under "contribute to development" so as to make it very clear that no one else needs to read them.

**Comment by janedupuy** [comment]
And I am a glorified copy editor. Also, your name is first alphabetically.

**Comment by marvinmarnold** [comment]
can you be more specific what you mean by indent? 

gurl, we gotta get your mind right. this project would not exist without you.

**Comment by janedupuy** [comment]
The more-graceful-looking web equivalent of this:

![image](https://cloud.githubusercontent.com/assets/13575695/9015139/73674d78-378c-11e5-92b7-7e32693de786.png)

**Comment by janedupuy** [comment]
Text on this page could also be smaller. See screen shot.
<img width="1280" alt="screen shot 2015-07-31 at 2 14 16 pm" src="https://cloud.githubusercontent.com/assets/13575695/9015405/5c43494c-378e-11e5-9d9c-b76f29078231.png">

**Comment by janedupuy** [comment]
This is a split-infinitive level request, but could we change "this app relies" to "the app relies"? On second thought I don't like the repetition of "this."

**Comment by marvinmarnold** [comment]
Moved conversation to peerio
