### ISSUE TITLE
Images for site

### ISSUE THREAD

**Issue by marvinmarnold** [marvinmarnold/stingraymappingproject.org#2]
https://upload.wikimedia.org/wikipedia/commons/4/48/BigBrother.jpg

https://upload.wikimedia.org/wikipedia/commons/8/8d/Feliz_1984.JPG

https://c2.staticflickr.com/8/7351/13851884344_116f3689ec_h.jpg

**Comment by marvinmarnold** [comment]
https://upload.wikimedia.org/wikipedia/commons/9/90/Kencf0618FacebookNetwork.jpg

**Comment by marvinmarnold** [comment]
Mary Ellen, where exactly are you thinking these images will go?

**Comment by janedupuy** [comment]
:) Not sure, had just made a note that I was supposed to find images. Where do you think we need them? The first three/four swipe pages for the app? Plus the front page of the website (was that why you left a gap between the first sentence and "protect yourself"?)?

**Comment by marvinmarnold** [comment]
I don't have any strong thoughts on where things should go right now. FYI [this site](http://www.flaticon.com/) has a bunch of icons.

**Comment by janedupuy** [comment]
Oh great! A photographer friend with some sense of aesthetics is also into the project. I may enlist his help in thinking about this stuff, what do you think? Maybe he and I could think some things through first and then we could all talk about it while you do the programming?

One artist friend is also into helping make a logo, but she's out of town and can't think about it for another week.

**Comment by janedupuy** [comment]
I wound up clearing my schedule for tomorrow pm and Joe (photographer) says he's free between 3:30 and 6 tomorrow. What's going on with the meeting with Mr. Bob, and would it make sense for me to be there for that and meet with Joe afterward or for you to just meet with him alone and me to meet with Joe during that same time? and either way would you be free after that meeting to talk with Joe and me about images for the site and app? 

This is all assuming we want his help, of course. I haven't done this kind of thing with him before so I don't know how useful he'll be, just figure anybody has a better eye for design than I do :)

**Comment by marvinmarnold** [comment]
You seem to have a pretty good eye. The more the merrier. I think Bob and I are meeting around 4 but its not set in stone. Wanna join us then and then we can meet Joe at 5?

**Comment by janedupuy** [comment]
Sure!

**Comment by janedupuy** [comment]
We won't then have time to hash anything out beforehand, but you don't mind
being in on the brainstorm? or we could work separately for a min first.

**Comment by marvinmarnold** [comment]
Your call on if I need to be there for brainstorming. 

I also edited the names of other people in the comments. We probably shouldn't use anybody's name who hasn't officially gotten on board. This is publicly available.

**Comment by janedupuy** [comment]
Wait, what comments are publicly available?

**Comment by janedupuy** [comment]
Oh, GitHub is? How available?

**Comment by marvinmarnold** [comment]
This is all 100% public. Sorry if that wasn't clear. Feel free to go back and edit/remove.

**Comment by janedupuy** [comment]
:D Have you been following the debate about apologizing? Everybody got
into this
video
https://nakedsecurity.sophos.com/2014/05/08/researchers-find-post-snowden-chill-stifling-our-search-terms/?utm_source=Naked%2520Security%2520-%2520Feed&utm_medium=feed&utm_content=rss2&utm_campaign=Feed&utm_reader=feedly
and
we all started trying to say that we were sorry less often, but after much
debate we decided to keep "I'm sorry I wasn't more clear" because it's such
a good way to remind people that it really was clear and they missed it.
I'm sure in this case that it was quite clear. I've just taken to assuming
that everything you do is top-secret. Our conversations in your office are
in an invisible encrypted sound-proof shell, right?

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
