### ISSUE TITLE
Learn page copy

### ISSUE THREAD

**Issue by marvinmarnold** [marvinmarnold/stingraymappingproject.org#5]
I think we should use your buttons to take people to these articles, something like the below. I'm not married to any of these articles or to this wording or order, so change anything.

STINGRAYS:

Portable devices that imitate cell phone towers https://www.aclu.org/issues/privacy-technology/surveillance-technologies/stingray-tracking-devices

Police use them to collect information from target phones and any others within range http://www.usatoday.com/story/news/nation/2013/12/08/cellphone-data-spying-nsa-police/3902809/

Often used without warrants http://www.slate.com/articles/technology/future_tense/2014/11/stingrays_imsi_catchers_how_local_law_enforcement_uses_an_invasive_surveillance.2.html

May be used to spy on protestors http://wgntv.com/2014/12/07/lawsuit-filed-against-chicago-police-department-over-concerns-of-phone-interceptions/ - or - http://chicago.cbslocal.com/2014/12/06/activists-say-chicago-police-used-stingray-eavesdropping-technology-during-protests/

Police and the FBI have worked to keep them secret http://www.baltimoresun.com/news/maryland/baltimore-city/bs-md-ci-stingray-case-20150408-story.html#page=1

**Comment by janedupuy** [comment]
New idea: let's ditch the buttons and just have sentences / bullet points that are also article links.

Also edited sentences and links:

![image](https://cloud.githubusercontent.com/assets/13575695/8990773/0d076496-36ba-11e5-9e79-3a35084b29aa.png)

Don't know why that pasted in in such a strange way - can you see it?

**Comment by janedupuy** [comment]
Hm. How did you get your text into this thread in a normal format without retyping everything?

**Comment by janedupuy** [comment]
![image](https://cloud.githubusercontent.com/assets/13575695/8991063/b392f144-36bb-11e5-98c9-231300656798.png)

**Comment by marvinmarnold** [comment]
It won't let you copy and paste?

**Comment by janedupuy** [comment]
When I do it makes it into those png images above.

**Comment by marvinmarnold** [comment]
That's pretty strange. Could you please use pastebin.com to include lots of words so i can easily copy? We can resolve the github pasting issue during our next 7h marathon.

**Comment by janedupuy** [comment]
STINGRAYS

Mimic cell phone towers, forcing your phone to connect to them and release private information to police
https://www.aclu.org/issues/privacy-technology/surveillance-technologies/stingray-tracking-devices

Mobile, suitcase-sized, and often installed in police vehicles

Collect information from target phones and any others within range http://www.usatoday.com/story/news/nation/2013/12/08/cellphone-data-spying-nsa-police/3902809/

Often used without warrants
http://www.slate.com/articles/technology/future_tense/2014/11/stingrays_imsi_catchers_how_local_law_enforcement_uses_an_invasive_surveillance.single.html

May be used to spy on protestors http://wgntv.com/2014/12/07/lawsuit-filed-against-chicago-police-department-over-concerns-of-phone-interceptions/

Kept secret from the public and often even from the courts
http://www.baltimoresun.com/news/maryland/baltimore-city/bs-md-ci-stingray-case-20150408-story.html#page=1

[How should we deal on this page with this recent FBI statement? It feels as if we should include it if we’re including articles discussing the NDA, but it’s not completely clear to me what its ramifications are]
http://www.rt.com/usa/259105-fbi-stingray-nondisclosure-agreement/

**Comment by marvinmarnold** [comment]
<h1>STINGRAYS</h1>
  <p class="learn-bullet text-center"><a href="https://www.aclu.org/issues/privacy-technology/surveillance-technologies/stingray-tracking-devices">Mimic cell phone towers</a>, forcing your phone to connect to them and release private information to police</p>

  <p class="learn-bullet text-center">Mobile, suitcase-sized, and often installed in police vehicles</p>

  <p class="learn-bullet text-center">Collect information from target phones and any <a href="http://www.usatoday.com/story/news/nation/2013/12/08/cellphone-data-spying-nsa-police/3902809/">others within range</a></p>

  <p class="learn-bullet text-center">Often used <a href="http://www.slate.com/articles/technology/future_tense/2014/11/stingrays_imsi_catchers_how_local_law_enforcement_uses_an_invasive_surveillance.single.html">without warrants</a></p>

  <p class="learn-bullet text-center">May be used to <a href="http://wgntv.com/2014/12/07/lawsuit-filed-against-chicago-police-department-over-concerns-of-phone-interceptions/">spy on protestors</a></p>

  <p class="learn-bullet text-center">Kept <a href="http://www.baltimoresun.com/news/maryland/baltimore-city/bs-md-ci-stingray-case-20150408-story.html#page=1">secret from the public</a> and often even from the courts</p>

  <p class="learn-bullet text-center">Something <a href="http://www.rt.com/usa/259105-fbi-stingray-nondisclosure-agreement/">ELSE</a></p>

**Comment by janedupuy** [comment]
I think these could be smaller and aligned with the left side of the page. Here's what it looks like on my screen now:
<img width="1280" alt="screen shot 2015-07-31 at 2 05 37 pm" src="https://cloud.githubusercontent.com/assets/13575695/9015248/42775f5e-378d-11e5-912b-7d4a3a36a37e.png">

**Comment by marvinmarnold** [comment]
Moved conversation to peerio
