### ISSUE TITLE
Information may harm people

### ISSUE THREAD

**Issue by janedupuy** [marvinmarnold/stingraymappingproject.org#7]
B: "It may be worth thinking through the potential psychological and behavioral implications of knowing that you are subject to Stingray surveillance or knowing where there is active Stingray surveillance.  I suspect people may have very mixed reactions to that information.  What potential harm might that cause?  How could you minimize the potential harm?"

**Comment by janedupuy** [comment]
Me: "I hadn’t thought that the psychological implications related to knowing where there’s active Stingray surveillance would be too significant since they’re by definition not static and can get what they need quickly – that is, no one anyone should be learning that they’re being watched daily or anything of that sort. But is that what came to mind for you? If so, I should clarify in the proposal. Is there a standard way to deal with potential psychological fallout, though? Should we say that we’ll direct people to a list of free counseling resources?"

What are your thoughts about this?

**Comment by marvinmarnold** [comment]
In general, I think making people aware of privacy issues risks causing damage by scarring them. That's still not very well understood but I can think of two studies that address this http://www.pen.org/global-chill https://nakedsecurity.sophos.com/2014/05/08/researchers-find-post-snowden-chill-stifling-our-search-terms/?utm_source=Naked%2520Security%2520-%2520Feed&utm_medium=feed&utm_content=rss2&utm_campaign=Feed&utm_reader=feedly

It may be helpful to talk about the general issue. I'm not sure how to be more specific to Stingrays. I'm also not clear what she was specific harms Becky was suspecting. We could make some up but I think it would be speculation at this point.
