### ISSUE TITLE
Contaminating data by making public in real time

### ISSUE THREAD

**Issue by janedupuy** [marvinmarnold/stingraymappingproject.org#8]
B: "...providing the data in real time is a bit unprecedented in social science research and probably not terribly strategic (for the purpose of research, not advocacy).  There is a real risk of contamination if you’ve got people who are using the app, tracking the use of Stingrays, and either participating in or avoiding events because of Stingray use (and/or other forms of surveillance).  I absolutely applaud your interest in making the data immediately and publicly available.  But at the same time, I think that muddies the meaning – and ultimately utility – of the data for research."

**Comment by janedupuy** [comment]
No action steps related to this but sharing my answer anyway in case you have thoughts to add:

Re: the trouble with providing the data in real time, are you thinking of the map on the website or the data download feature (which would be a spreadsheet)? The latter, intended for other researchers for transparency’s sake, could possibly be left out. It sounds as though you’re talking more about the map, though, and it’s pretty central to the project. I don’t expect it to muddy the data much, because we imagine that people will primarily pick up Stingrays either in their neighborhoods (where they’d in theory need to be in any case) or at protests. I doubt that people would avoid demonstrations because they’ve become aware of the threat of Stingrays through this project, since they’ll have the assurance of knowing that their phones will notify them if they’re being hacked and since they could also put their phones in airplane mode if they don’t want it to happen at all. I’m not sure whether anyone would attend an event that they wouldn’t otherwise have attended just because they want to check for Stingrays, but our main base of users will probably be activists, so it’s likely that Stingrays detected at protests would have been detected by another user in any case. But even if I’m wrong about all of that, I guess it’s a problem we’ll just have to contend with and discuss if we write a paper about this data.

**Comment by marvinmarnold** [comment]
I like all your comments. I also think the proposed strategy for data normalization will reduce some of this. We are no longer talking about looking at the gross number of points observed. Instead, it's a binary result per time-area. If other people turn their phones off, leave, etc, it won't effect the overall reading in that bucket.

I guess if everybody who gets a red reading immediately turns off their own phones, then it will shorten the amount of time stingrays appear to be in the area. In that case, we should avoid doing any fine grained time analysis (down to the minute). So maybe we won't be able to say that a Stingray was there for %57 of the protest but could probably say it was there in the morning and not in the afternoon.

**Comment by janedupuy** [comment]
Yep. I think the bucket data normalization idea assumes total coverage, though, which is the issue we keep running into when we think about analysis. I guess we just have to go for total coverage. :)

Good point about timing. I think it would also be fine just to make it a daily binary: a Stingray showed up on this day of this protest, or it didn't.
